### ISSUE TITLE
es-spark

### ISSUE THREAD

**Issue by styleNie** [gitphill/es-spark#1]
thanks for your example for es-spark; I have some question. 
Is the information of elasticsearch set up in the docker-compose.yml ?
I try to use es and spark in win7,but failed ,here my code

```
import org.apache.spark.SparkConf
import org.apache.spark.SparkContext
import org.elasticsearch.spark._
import org.elasticsearch.spark.rdd.EsSpark
object Tryout {
  def main(args: Array[String]) {
    val conf = new SparkConf().setAppName("Tryout").setMaster("local[8]")
    conf.set("es.index.auto.create", "true")
    conf.set("es.resource", "contacts/people")
    conf.set("es.resource.read","contacts/people")
    conf.set("es.resource.write","spark/docs")
    conf.set("es.nodes","localhost")
    conf.set("es.port","9200")
    conf.set("spark.driver.allowMultipleContexts", "true")

    val sc = new SparkContext(conf)
    val numbers = Map("one" -> 1, "two" -> 2, "three" -> 3)
    val airports = Map("arrival" -> "Otopeni", "SFO" -> "San Fran")
    sc.makeRDD(Seq(numbers, airports)).saveToEs("spark/docs")
    sc.stop()
  }
}

```
and the maven pom
```
 <properties>
        <spark.version>1.5.2</spark.version>
        <scala.binary.version>2.10</scala.binary.version>
    </properties>
    <dependencies>
    <dependency>
        <groupId>org.apache.spark</groupId>
        <artifactId>spark-core_${scala.binary.version}</artifactId>
        <version>${spark.version}</version>
    </dependency>
        <dependency>
            <groupId>org.elasticsearch</groupId>
            <artifactId>elasticsearch-hadoop</artifactId>
            <version>2.1.0.Beta2</version>
        </dependency>
    </dependencies>

```
but I get error 
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 4 in stage 0.0 failed 1 times, most recent failure: Lost task 4.0 in stage 0.0 (TID 4, localhost): java.lang.StringIndexOutOfBoundsException: String index out of range: -1

can you help me? thanks!

**Comment by gitphill** [comment]
Hi, I would suggest using the Vagrant development environment provided. Install VirtualBox and Vagrant then follow the README. This should get you up and running so that you can at least see it running and play with the Scala. Once you grasp the basic, then I would look at getting it running in Windows - if you really must :)

**Comment by styleNie** [comment]
thanks,I'll try it.
